language: python

python:
  - "3.6"
  - "3.7"

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip

install:
  - if [[ "$TEST_MODE" == "DOCS" ]]; then pip install .; fi
  - if [[ "$TEST_MODE" != "DOCS" ]]; then pip install flake8 flake8-docstrings; fi

script:
  - if [[ "$TEST_MODE" == "DOCS" ]]; then python tools/make_transforms_docs.py check README.md; fi
  - if [[ "$TEST_MODE" != "DOCS" ]]; then flake8; fi
